### PR TITLE
Refactor as promised

### PR DESCRIPTION
**Pull request by kscholty**
As promised I took some time to re-factor the code.

# What did I do

* Created modules for 
  * throttle/regen `throttle.[ch]` 
  * i2cFunctions `i2cHelpers.[ch]`
  * motor control `motor.[ch]`
  * lcd / output handling `lcd.[ch]`

Each module is now called from the main loop instead of having the code in there directly. 
Furthermore, I moved defines belonging to a module to the respective header
Each module has an init function that is called once before the main loop starts. The motor init function should be called early, since it sets the DAC addresses to disabled. ( a pulldown might be appropriate here to make sure they are already set at startup).

# Main logic changes

I tried to get rid of the reapeating code using ifs to distinguish between different states.
Instead I created arrays that contain the parameters for different states and have an index to access the one that is used for the current situation.

E.g. instaedof asking
```
if(throttleLeftEnabled)
   calculate with MAX_VALUE_OF_LEFT_TROTTLE;
else if(throttelRightEnabled)
  calculate with MAX_VALUE_OF_RIGHT_TROTTLE;
else 
  calculate with MAX_VALUE_OF_SOMETHINGELSE;
```

the new code has an array that contains the three differen MAX values and executes
```
calculate with MAX_VALUES[activeThrottle]
```
This has beed done for mapping the throttle and regen positions from the ADC values and for mapping the positions to motor output values for the different motors.

One of the main changes is that the position of the throttle and regen position is now expressed as a per-mille value.
For the throttle 0-499 indicates reverse, 500 is neutral and 501...1000 is forward.
For regen it's simply 0...1000
These values will be smoothed (gliding average) instead of the raw values from the ADC, since this makes it independent from the throttle used and has not to be re-initialzed when the throttle changes.

# Output handling

Output has been moved to a seperate module. Since we don't have access to all the intermediate values anymore, the lcd module has some storage (called status) that can store these values. To set them setters have been implemented and are called from the calulation functions (throttle/motor). 
I did not change the output function, because I assume that is temporary anyway, but I see some potential for optimization here as well.

# General remarks
* Please be careful when sizing arrays. Several of them were too small, especially the ones you used to generate the texts for output, but also the one that stores the command for the DACs. 

* I might have broken something. It compiles, but I obviously I don't have your setup to test the code. If you find something not working, I can support if you like.

* I disbled (`#if 0`) the code in `nc_lcd.c` since it somehow found it's way into my makefiles over and over again. So you have to re-activate if you plan to work on it.

* I added the new files to the Makefile. I don't know which build method you use (looked like VS-Code in the video). Depending on that you might  have to add the new files to the process.

* Have fun with it and let mne knwo how it worked out for you :-)

### CODE REVIEW

**Comment by digimer** [comment]
Thank you so much for this. The rush is over, and I'm hoping to start working in this over the weekend!

**Comment by digimer** [comment]
Hi again, just an update; I got this PR pulled to my local system and built it successfully, but the stm32 stopped responding. I'll debug more next, but fyi that I've working on this again. :)

**Comment by digimer** [comment]
I made a short video showing what I'm seeing. If you want to message me on discord, irc, whatsapp, etc, let me know and perhaps we can debug this directly, if you're keen and have the spoons. :)

https://www.youtube.com/watch?v=GrfqpdRD01c

**Comment by kscholty** [comment]
Sure. Might be challenging to find a slot with our time difference but I'd love to.
My discord username is _keyem_2002_. 

And just for be to start thinking: You don't see any output on the uart?
If so two things cross my mind that might cause that:

1) Main switch is off or not correctly detected.
    Try to deactivate the test (or just the return)
    ```
      if (status.mainSwitch == 0) {
         return;
      }
   ``` 
    at the beginning of `lcdPrint()`

2) The UART is not correctly initialized, since I moved the init to a later point in time
     Move the call to `lcdInit()` directly after the call to `MX_DMA_Init();` further up in `main()`

If both does not help more thinking is required. I'd start with 1) and then 2)

**Comment by digimer** [comment]
It's tied to the display switch, yes. When I turn the switch off (to turn off the LCD), UART output starts. Now that I know this, I'll see if I can get it working all the time.

**Comment by digimer** [comment]
Confirmed, that test was the problem. UART is working well now.

**Comment by digimer** [comment]
Hi @kscholty , I've invited you to be a contributor to the main Mermaid's Rest repo. I created a new PR based on our collab editing session plus some cleanup. Once I know you can work on that one, I'll close this one and add you as a reviewer for that one. 
https://github.com/digimer/Mermaids-Rest/pull/21

**Pull request merged**
